server:
  port: 10011

eureka:
  server:
    port: 10010
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 45
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/

zuul:
  add-host-header: true
  host:
      connect-timeout-millis: 50000
      socket-timeout-millis:  50000
  routes:

      MAINTENANCE:
          path: /maintenance/**
          serviceId: MAINTENANCE
          sensitive-headers: "*"
          custom-sensitive-headers: true
      BUSINESS:
          path: /business/**
          serviceId: BUSINESS
          sensitive-headers: "*"
          custom-sensitive-headers: true

ribbon:
  ConnectTimeout: 10000
  ReadTimeout:  10000

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
                isolation:
                    thread:
                        timeoutInMilliseconds:  10000